# Generated by Django 5.0.7 on 2024-07-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(default=None)),
                ('picture', models.TextField(default=None)),
                ('likes', models.BigIntegerField(default=0)),
                ('date_time_created', models.DateField(auto_now_add=True)),
                ('date_time_edited', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=256)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.posts')),
            ],
        ),
    ]
