# Generated by Django 5.0.7 on 2024-07-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_posts_content_alter_posts_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['post_id']},
        ),
    ]
