name: Tests and linters

on: 
  push:
      branches: [master]

jobs:
     build:
           runs-on: ubuntu-latest     
       
           steps:
                
                 - uses: action/checkout@master
                   with:
                      fetch-depth: 0
                      
                 - name: Python setup
                   uses: actions/setup-python@v2
                   with:
                        python-version: "3.11"
                
     
