name: Tests and linters

on: 
  push:
      branches: [master]

jobs:
     test:
       name: Run tests
       runs-on: windows-latest
       steps:
            
            uses: action/checkout@v4

            
            uses: actions/setup-python@v4

            
            run: pip install -r requirements.txt

            
            run: cd api

            
            run: pytest unit-tests.py

            
            run: pytest unit-tests.py
     
