name: Tests and linters

on: 
  push:
      branches: [master]

jobs:
     test:
           runs-on: ubuntu-latest     
       
           steps:
                
           - name: Repository checkout
             uses: actions/checkout@v4             
                      
           - name: Python setup
             uses: actions/setup-python@v4
             with:
               python-version: "3.11"

           - name: Execute dependencies
             run: pip install -r requirements.txt
             
           - name: Run unit-tests
             run: pytest photoview/api/unit-tests

           - name: Run integrate-tests
             run: pytest photoview/api/integrate-test

    
         
     
