name: Tests and linters

on: 
  push:
      branches: [master]

jobs:
     build:
           runs-on: ubuntu-latest     
       
           steps:
                - name: Repo checkout
                  uses: action/checkout@v2
                  with:
                      fetch-depth: 0
                      
                - name: Python setup
                  uses: actions/setup-python@v2
                  with:
                      python-version: "3.11"
                
     
