name: Tests and linters

on: 
  push:
      branches: [master]

jobs:
     test:
           runs-on: ubuntu-latest     

           services:
              # Label used to access the service container
              postgres:
                # Docker Hub image
                image: postgres
                # Provide the password for postgres
                env:
                  POSTGRES_PASSWORD: 8565
                # Set health checks to wait until postgres has started
                options: >-
                  --health-cmd pg_isready
                  --health-interval 10s
                  --health-timeout 5s
                  --health-retries 5
                ports:
                  # Maps tcp port 5432 on service container to the host
                  - 5432:5432
          
           steps:
                
           - name: Repository checkout
             uses: actions/checkout@v4             
                      
           - name: Python setup
             uses: actions/setup-python@v4
             with:
               python-version: "3.11"

           - name: Execute dependencies
             run: pip install -r requirements.txt
             
           - name: Run unit-tests
             run: pytest api/unit-tests.py

           - name: Run integrate-tests
             run: pytest api/integrate-test.py

    
         
     
